chore: add package update check and upgrade scripts for dotfiles
- Introduced a script to check for outdated pacman and AUR packages defined in dotfiles
- Added a script to upgrade outdated pacman and AUR packages automatically
- Updated Makefile to include an 'upgrade' target for package updates
- Modified install script to run the package check during setup process

These changes facilitate easier maintenance and ensure dotfile-managed packages stay up to date.

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -76,3 +76,7 @@ log_section .dotbot/install
 with_time sudo .dotbot/install
 echo
 echo
+
+# Check for outdated packages
+log_section "Checking for outdated packages"
+script/check_outdated_packages || true  # Don't fail install if updates are available
